INSERT INTO users (name, age) VALUES ("Joanna", 27);
INSERT INTO users (name, age) VALUES ("Lisa", 25);
INSERT INTO users (name, age) VALUES ("Vicki", 24);
INSERT INTO users (name, age) VALUES ("Emily", 26);
INSERT INTO users (name, age) VALUES ("Melanie", 27);
INSERT INTO users (name, age) VALUES ("Morgan", 26);
INSERT INTO users (name, age) VALUES ("Peter", 27);
INSERT INTO users (name, age) VALUES ("Raven", 24);
INSERT INTO users (name, age) VALUES ("Kayla", 27);
INSERT INTO users (name, age) VALUES ("Carol", 65);
INSERT INTO users (name, age) VALUES ("Barry", 62);
INSERT INTO users (name, age) VALUES ("Charlotte", 2);
INSERT INTO users (name, age) VALUES ("Matthew", 26);
INSERT INTO users (name, age) VALUES ("Will", 25);
INSERT INTO users (name, age) VALUES ("Tommy", 27);
INSERT INTO users (name, age) VALUES ("Kylie", 29);
INSERT INTO users (name, age) VALUES ("Pat", 65);
INSERT INTO users (name, age) VALUES ("Rob", 65);
INSERT INTO users (name, age) VALUES ("Kari", 32);
INSERT INTO users (name, age) VALUES ("David", 37);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Moving", "charity", 2000, 062319, 070119);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("First Project", "music", 15000, 102519, 122519);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Second Project", "art", 8000, 090119, 111119);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Third Project", "art", 150, 111119, 122619);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fourth Project", "art", 8282, 120119, 121019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fifth Project", "art", 90000, 062319, 080119);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sixth Project", "art", 10000000, 060119, 010120);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Seventh Project", "art", 40, 012020, 020220);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eighth Project", "art", 19482, 070119, 080119);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ninth Project", "art", 1000292, 012920, 060120);

INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (55, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 10, 10);
