INSERT INTO users (name, age) VALUES ("Ricky", 29);
INSERT INTO users (name, age) VALUES ("Gavin", 27);
INSERT INTO users (name, age) VALUES ("Rubab", 27);
INSERT INTO users (name, age) VALUES ("Micah", 29);
INSERT INTO users (name, age) VALUES ("Jaylen", 22);
INSERT INTO users (name, age) VALUES ("Candida", 56);
INSERT INTO users (name, age) VALUES ("Zainab", 28);
INSERT INTO users (name, age) VALUES ("Jessica", 36);
INSERT INTO users (name, age) VALUES ("Jamie", 33);
INSERT INTO users (name, age) VALUES ("Kathy", 34);
INSERT INTO users (name, age) VALUES ("Aishah", 15);
INSERT INTO users (name, age) VALUES ("Lupe", 35);
INSERT INTO users (name, age) VALUES ("Ryan", 29);
INSERT INTO users (name, age) VALUES ("Al", 42);
INSERT INTO users (name, age) VALUES ("Latrell", 29);
INSERT INTO users (name, age) VALUES ("Athony", 51);
INSERT INTO users (name, age) VALUES ("Michael", 42);
INSERT INTO users (name, age) VALUES ("Jennifer", 38);
INSERT INTO users (name, age) VALUES ("Jimmy", 19);
INSERT INTO users (name, age) VALUES ("Jayson", 21);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New York Drawings", "art", 10000, "6/2019", "7/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cosial Justice App", "start-up", 40000, "3/2019", "7/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("E-cig", "tobacco", 20000, "3/2019", "9/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Photo Project", "art", 3000, "5/2019", "8/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tee Shirt", "fashion", 6000, "7/2019", "8/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mobile Game", "tech", 50000, "7/2019", "9/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pizzadoughnuts", "food", 2000, "6/2019", "7/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sneakerz", "fashion", 20000, "9/2019", "12/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("I See Rivers", "music", 5000, "5/2019", "7/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sports Highlights Project", "sports", 5000, "7/2019", "8/2019");

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 17, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 19, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 12, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20000, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (52, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (78, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 6, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (350, 11, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 19, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (95, 8, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 20, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 14, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 3, 9);

